name: mind_cows
description: My new flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ^3.22.1

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.2.3
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_gutter: ^2.2.0
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  injectable: ^2.4.4
  intl: ^0.19.0
  logger: ^2.3.0
  go_router: ^14.2.8
  flutter_hooks: ^0.20.5

  skeletonizer: ^1.4.2
  top_snackbar_flutter: ^3.1.0

  lottie: ^3.1.2
  rxdart: ^0.28.0

  sized_context: ^1.0.0+4
  spider: ^4.2.2

  supabase_flutter: ^2.8.0
  shared_preferences: ^2.3.2

  uuid: ^4.5.1

  equatable: ^2.0.0

  firebase_crashlytics: ^4.1.3
  firebase_core: ^3.6.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.6.2
  json_serializable: ^6.2.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

  package_rename: ^1.7.1
  flutter_launcher_icons: "^0.14.1"
  flutter_native_splash: ^2.4.2
  icons_launcher: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
  - .env
  - assets/images/
  - assets/fonts/sniglet/
  - assets/fonts/poppins/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
    - family: Sniglet
      fonts:
        - asset: assets/fonts/sniglet/Sniglet-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

package_rename_config:
  android:
    app_name: "MindCows"
    package_name: "com.mindcows.app"
  ios:
    app_name: "MindCows"
    package_name: "com.mindcows.app"
